[hekad]
decoder_poolsize = 5
max_message_loops = 8
max_process_inject = 10
max_timer_inject  = 20
maxprocs = 4
plugin_chansize = 10
poolsize = 200

[StatsdInput]
address = "127.0.0.1:8125"

[StatAccumInput]
ticker_interval = 5

[TcpInput]
address = "127.0.0.1:5565"

[TcpInput2]
type = "TcpInput"
address = "127.0.0.1:5566"

[CounterFilter]

[StatsdFileOutput]
type = "FileOutput"
message_matcher = "Type == 'heka.statmetric'"
path = "log/statsdonly.log"
format = "json"

[LogOutput]
message_matcher = "Type == 'heka.counter-output'"
payload_only = true

[WhisperOutput]
base_path = "/var/run/hekad/whisper/db"
message_matcher = "Type == 'heka.statmetric'"
default_agg_method = 1
default_archive_info = [ [0, 30, 1440], [0, 900, 192], [0, 3600, 168], [0, 43200, 1456] ]

[DashboardOutput]
